// import 'package:flutter/widgets.dart';
//
// class MyIcons {
//   MyIcons._();
//
//   static const _kFontFam = 'MyFlutterApp';
//   static const String? _kFontPkg = null;
//
//   static const IconData award_alt_r =
//       IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData award_r =
//       IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData backspace_r =
//       IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData bag_alt_r =
//       IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData bag_r =
//       IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData bag_r_1 =
//       IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData bank_r =
//       IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData battery_charge_r =
//       IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData battery_r =
//       IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData bell_r =
//       IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData bolt_alt_r =
//       IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData bolt_r =
//       IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData bookmark_r =
//       IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData book_r =
//       IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData calendar_check_r =
//       IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData calendar_r =
//       IconData(0xe80f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData camera_r =
//       IconData(0xe810, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData card_r =
//       IconData(0xe811, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData cart_r =
//       IconData(0xe812, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData cash_r =
//       IconData(0xe813, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData chart_down_r =
//       IconData(0xe814, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData chart_line_r =
//       IconData(0xe815, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData chart_histogramm_r =
//       IconData(0xe816, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData chart_pie_r =
//       IconData(0xe817, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData chart_up_r =
//       IconData(0xe818, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData checkmark_r =
//       IconData(0xe819, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData chevron_down_r =
//       IconData(0xe81a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData chevron_left_r =
//       IconData(0xe81b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData chevron_right_r =
//       IconData(0xe81c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData chevron_up_r =
//       IconData(0xe81d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData clipboard_alt_r =
//       IconData(0xe81e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData clipboard_r =
//       IconData(0xe81f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData clock_r =
//       IconData(0xe820, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData close_r =
//       IconData(0xe821, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData close_circle_r =
//       IconData(0xe822, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData cloud_download_r =
//       IconData(0xe823, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData cloud_r =
//       IconData(0xe824, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData code_r =
//       IconData(0xe825, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData coins_r =
//       IconData(0xe826, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData comments_r =
//       IconData(0xe827, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData comment_r =
//       IconData(0xe828, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData crosshair_r =
//       IconData(0xe829, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData copy_r =
//       IconData(0xe82a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData cup_r =
//       IconData(0xe82b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData dashboard_r =
//       IconData(0xe82c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData desktop_r =
//       IconData(0xe82d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData dislike_r =
//       IconData(0xe82e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData dots_alt_r =
//       IconData(0xe82f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData dollar_r =
//       IconData(0xe830, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData dots_r =
//       IconData(0xe831, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData download_r =
//       IconData(0xe832, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData education_r =
//       IconData(0xe833, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData email_r =
//       IconData(0xe834, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData euro_r =
//       IconData(0xe835, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData exchange_r =
//       IconData(0xe836, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData eye_closed_r =
//       IconData(0xe837, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData eye_r =
//       IconData(0xe838, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData file_alt_r =
//       IconData(0xe839, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData file_r =
//       IconData(0xe83a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData filter_r =
//       IconData(0xe83b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData flag_alt_r =
//       IconData(0xe83c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData flag_r =
//       IconData(0xe83d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData focus_r =
//       IconData(0xe83e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData folder_add_r =
//       IconData(0xe83f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData folder_check_r =
//       IconData(0xe840, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData folder_delete_r =
//       IconData(0xe841, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData folder_r =
//       IconData(0xe842, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData forward_r =
//       IconData(0xe843, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData gamepad_r =
//       IconData(0xe844, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData gear_r =
//       IconData(0xe845, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData gear_alt_r =
//       IconData(0xe846, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData gift_r =
//       IconData(0xe847, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData headphones_r =
//       IconData(0xe848, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData home_r =
//       IconData(0xe849, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData image_r =
//       IconData(0xe84a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData key_r =
//       IconData(0xe84b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData lightbulb_r =
//       IconData(0xe84c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData like_r =
//       IconData(0xe84d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData link_r =
//       IconData(0xe84e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData location_r =
//       IconData(0xe84f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData lock_opened_r =
//       IconData(0xe850, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData lock_r =
//       IconData(0xe851, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData magnify_minus_r =
//       IconData(0xe852, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData magnify_plus_r =
//       IconData(0xe853, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData menu_r =
//       IconData(0xe854, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData microphone_r =
//       IconData(0xe855, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData minus_r =
//       IconData(0xe856, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData minus_circle_r =
//       IconData(0xe857, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData mobile_r =
//       IconData(0xe858, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData moon_r =
//       IconData(0xe859, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData mouse_r =
//       IconData(0xe85a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData music_r =
//       IconData(0xe85b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData no_entry_r =
//       IconData(0xe85c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData note_r =
//       IconData(0xe85d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData pause_r =
//       IconData(0xe85e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData pencil_r =
//       IconData(0xe85f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData phone_r =
//       IconData(0xe860, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData pin_r =
//       IconData(0xe861, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData plane_r =
//       IconData(0xe862, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData planet_r =
//       IconData(0xe863, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData play_r =
//       IconData(0xe864, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData pluc_circle_r =
//       IconData(0xe865, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData plus_r =
//       IconData(0xe866, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData pound_r =
//       IconData(0xe867, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData power_r =
//       IconData(0xe868, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData presentation_r =
//       IconData(0xe869, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData print_r =
//       IconData(0xe86a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData question_circle_r =
//       IconData(0xe86b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData refresh_r =
//       IconData(0xe86c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData reply_r =
//       IconData(0xe86d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData rocket_r =
//       IconData(0xe86e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData ruble_r =
//       IconData(0xe86f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData sandwatch_alt_r =
//       IconData(0xe870, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData sandwatch_r =
//       IconData(0xe871, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData save_r =
//       IconData(0xe872, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData search_r =
//       IconData(0xe873, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData send_r =
//       IconData(0xe874, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData shield_check_r =
//       IconData(0xe875, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData shield_r =
//       IconData(0xe876, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData sitemap_r =
//       IconData(0xe877, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData sliders_r =
//       IconData(0xe878, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData smile_confuse_r =
//       IconData(0xe879, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData smile_happy_r =
//       IconData(0xe87a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData smile_sad_r =
//       IconData(0xe87b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData sort_r =
//       IconData(0xe87c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData stack_r =
//       IconData(0xe87d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData star_r =
//       IconData(0xe87e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData star_r_1 =
//       IconData(0xe87f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData sun_r =
//       IconData(0xe880, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData tag_r =
//       IconData(0xe881, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData trash_alt_r =
//       IconData(0xe882, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData trash_r =
//       IconData(0xe883, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData umbrella_r =
//       IconData(0xe884, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData upload_r =
//       IconData(0xe885, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData user_r =
//       IconData(0xe886, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData video_r =
//       IconData(0xe887, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData volume_r =
//       IconData(0xe888, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData wallet_r =
//       IconData(0xe889, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData watch_r =
//       IconData(0xe88a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData wifi_r =
//       IconData(0xe88b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData yen_r =
//       IconData(0xe88c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData alarm_r =
//       IconData(0xe88d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData alert_circle_r =
//       IconData(0xe88e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData apps_r =
//       IconData(0xe88f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData archive_r =
//       IconData(0xe890, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData arrow_down_r =
//       IconData(0xe891, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData arrow_left_r =
//       IconData(0xe892, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData arrow_right_r =
//       IconData(0xe893, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData arrow_up_r =
//       IconData(0xe894, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData attach_r =
//       IconData(0xe895, fontFamily: _kFontFam, fontPackage: _kFontPkg);
// }
